Project xmemory {
  database_type : "PostgreSQL"
  note : "Description du project"
}

Table Memoire {
  ID int [pk]
  Topic varchar (200)
  Abstract varchar
  Resume varchar
  Matricule varchar(20)
  Annee_Scolaire varchar(20)
  Niveau Niveau
  Author int [ref: > User.ID]
  Filiere int [ref: > Filiere.ID]
  Encadrant int [ref: > Professeur.ID]
}

Enum Niveau {
  Licence
  Master
}

Table User {
  ID int [pk]
  Name varchar(50)
  Email varchar(60)
  Created_At datetime
}

Table Professeur {
  ID int [pk]
  Nom varchar(50)
  Titre varchar(100)
  Type ProfesseurType
}

Enum ProfesseurType {
  Vaccataire
  Permanent
}

Table Filiere {
  ID int [pk]
  Label varchar(50)
}