version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
  save_cache_cmd:
    steps:
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  install_deps_cmd:
    steps:
      - run:
          name: Install Dependencies
          command: go mod download

executors:
  docker-executor:
    docker:
      - image: cimg/go:1.21.0
  machine-executor:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true

jobs:
  build:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache_cmd
      - install_deps_cmd
      - save_cache_cmd

      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  deploy:
    executor: machine-executor
    steps:
      - run: ""

workflows:
  sample:
    jobs:
      - build